### ISSUE TITLE
Default splitter size when maximised needs adjusting

### ISSUE THREAD

**Issue by apexlee** [Eoinocal/Halite#25]
On a fresh run, the default splitter size for the detailed view (peers, trackers, etc) is too aggressive. It should be closer to 50/50 instead of the current value.

See screenshot for more details
![splitter](https://cloud.githubusercontent.com/assets/5897198/9140456/4731c290-3d29-11e5-9ff6-757ca8c6d13b.jpg)

**Comment by Eoinocal** [comment]
Thanks for the report. 

Having the splitter rezise proportionaly with the window was disabled because it used to cause the splitter position to "creep up" each time Halite was launched. The fix was easy enough I just never got around to it.

It is now fixed in b5c34d0cb3e789c78177486605c37bc9aa137351
